name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  lint-format-type-checkmanifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x  # Specify the Python version you want to use

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy check-manifest

      - name: Lint Code
        run: ruff check .

      - name: Format Code
        run: black --check --diff .

      - name: Type Check
        run: mypy --strict src tests

      - name: Check Manifest
        run: check-manifest

  pytest:
    needs: lint-format-type-checkmanifest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # Add the Python versions you want to test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests and Calculate Coverage
        run: pytest